### ISSUE TITLE
Failing to detect bubble column afk machine

### ISSUE THREAD

**Issue by Uboaaaaa** [LapisPlugins/AFKPlus#12]
Hi, there's this player on my server afking using upflowing bubble column produced by soul sand (kept hopping up and down). They've been there for 6 hours but the plugin didn't detect it. There's absolutely no change in their yaw.

I'd like to know how the "movement" check works. If a player made change to their position but has not been looking around at all, will they be flagged for afk?

**Comment by Dart2112** [comment]
I'd suggest enabling "AggressiveAFKDetection" in the config, this setting is designed for dealing with AFK Machines

The next version will have separate look and move detection types

**Comment by Uboaaaaa** [comment]
Thanks! I'll turn it on and see how it works.
