### ISSUE TITLE
Suggestion: Prevent monsters from spawning around afk players.

### ISSUE THREAD

**Issue by Uboaaaaa** [LapisPlugins/AFKPlus#15]
Hi! I'm not sure whether this is possible, but I think it'll be a pretty useful feature to have!
If a player reached X time of being afk, disable the monster spawning around them.
This can be further specified into natual spawning and spawner spawning.
Can be useful to reduce the amount of lag especially in mob grinders!

**Comment by Dart2112** [comment]
I'm not sure if I can do that at the plugin level without reflection. But I'll look into it

**Comment by Dart2112** [comment]
So I've started looking into this more
I'm gonna try to do it but I'm not sure how well it will work since I can't just check which player mobs are spawning for. So I have to check if there is a player nearby who is or isn't AFK and make the decision to cancel the spawning event. 
I'm gonna do some more research and come back to this, so it probably won't be in this next major update.

**Comment by jamesgeddes** [comment]
I would argue that the player should spawn-proof the area rather than just nerfing spawns. If the player returns to find that their avatar died while they were AFK then that will teach them to make their areas safer! :laughing:

**Comment by Dart2112** [comment]
I've attempted to implement this but haven't rigorously tested it

**Comment by Uboaaaaa** [comment]
Gave the feature some testing, doesn't seem to work...

**Server version:** git-Paper-762 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
**Plugin version:** 3.3.2
**Configuration:**
```
Protections:
  MobSpawning: true
```

Mobs are clearly spawning on the minimap.
![image](https://user-images.githubusercontent.com/70588463/120711941-e382ee00-c4b7-11eb-989a-5a95bc55dddc.png)

**Comment by srnyx** [comment]
> I would argue that the player should spawn-proof the area rather than just nerfing spawns. If the player returns to find that their avatar died while they were AFK then that will teach them to make their areas safer! 😆 Jack o'Lanterns and carpet FTW!

I think that the setting should still be available for server administrators that want it.

**Comment by Dart2112** [comment]
From personal testing, this seems to have been fixed. The latest updates include a working version of this feature so for now, I am going to close this issue. If anyone encounters errors with it please make a new issue for it. 

Thank you very much to everyone in here for both the suggestion of this feature and the testing of it.
