### ISSUE TITLE
Suggestion: Essentials Hook

### ISSUE THREAD

**Issue by Uboaaaaa** [LapisPlugins/AFKPlus#16]
I found that many plugins out there uses the AFK status provided by _Essentials(X)_ plugin. For example [this one which skips night when players afk](https://www.spigotmc.org/resources/smoothsleep.32043/) and [this one labels players as afk in tablist](https://www.spigotmc.org/resources/tab-1-5-x-1-16-4.57806/). Even though _Essentials_' AFK detection is far less reliable compared to _AFKPlus_.
I think it would be very helpful if the plugin can hook with _Essentials_. For example people can disable the afk check provided by _Essentials_ and use AFKPlus instead, who will sync the player's afk status across the two plugins.

**Comment by Dart2112** [comment]
should now be working
