### ISSUE TITLE
Player name

### ISSUE THREAD

**Issue by jamesgeddes** [LapisPlugins/AFKPlus#17]
Trying to add a player to a team so that their player name is changed while they are AFK. For example,

`Example [AFK]`

How do you make the player
- join team `AFK` on AFKStart
- leave any team on AFKStop

I have made the "AFK" team and then tried
```
Commands:
  Action: "kick [PLAYER] You were AFK for too long!"
  AFKStart: "team join AFK"
  AFKStop: "team leave @s"
  Warn: ""
```
But the player is not added to the team.

**Comment by Dart2112** [comment]
https://github.com/Dart2112/AFKPlusPrefix
This project actually does this for you with a prefix, if you'd like I can add a suffix option aswell

**Comment by jamesgeddes** [comment]
Having the option would be good, but prefix works :smile: 

We will swap to that, thanks!

**Comment by Dart2112** [comment]
https://github.com/Dart2112/AFKPlusPrefix/releases/tag/1.2.0

Just added suffixes and cleaned up the code

**Comment by jamesgeddes** [comment]
Fantastic!! Thanks!
