### ISSUE TITLE
Customise AFK message

### ISSUE THREAD

**Issue by jamesgeddes** [LapisPlugins/AFKPlus#18]
We would like to be able to edit the AFK message. Currently it says

`[AFK+] Player is now AFK`

and

`[AFK+] Player is no longer AFK`

We would like it to say

`Player has decided to do some paint dehydration`

and

`Player got bored of paint dehydration`

**Bonus points**

It would be great if AFK start and stop messages could be selected from a list each time. Could have a start/stop pair that are chosen randomly.

**Comment by Dart2112** [comment]
You can edit these messages, they are in the messages.yml file in the AFKPlus plugin directory.
It should like the following by default
[https://imgur.com/91W4ZYX.png](url)

I can look into making an add on for random message pairs if you'd like

**Comment by Dart2112** [comment]
https://github.com/Dart2112/AFKPlusRandomMessages/releases/tag/1.0.0

Now done, you'll need the VERY latest version of AFKPlus which can be downloaded from Github at the link below
https://github.com/LapisPlugins/AFKPlus/raw/master/updater/AFKPlus/AFKPlus.jar

**Comment by jamesgeddes** [comment]
Legendary! Thanks!
