### ISSUE TITLE
Manual AFK

### ISSUE THREAD

**Issue by Mister-Muffin** [LapisPlugins/AFKPlus#19]
Hi there,
I already coded it myself, but the option that if you type `/afk` in chat it would mark you as AFK but not kick you would be nice.

**Comment by jamesgeddes** [comment]
You can already do this. You just need to configure the "actions" not to do anything when the player has been afk for a long time

**Comment by Mister-Muffin** [comment]
But will it kick me then when i go afk due to the AFK timeout?

**Comment by Dart2112** [comment]
> But will it kick me then when i go afk due to the AFK timeout?

Nope, the action is the only thing that happens, if it doesn't kick you then nothing happens. But its better to just set the time to action to be -1. 

`#Set to -1 to disable actions for this permission`

That way the player can be AFK forever and not be kicked. If you only want that to happen if you manually AFK then use your own solution. But this is how you could achieve something simular with the core plugin.

**Comment by Mister-Muffin** [comment]
Okay, thank you :+1:  :grinning:
