### ISSUE TITLE
Cannot install addons

### ISSUE THREAD

**Issue by baeumchen127** [LapisPlugins/AFKPlus#20]
I tried installing the AFKPlusPrefix add-on by putting the .zip file in my plugins folder. But this did not generate any other files etc after restarting. I even tried converting the .zip file into a .jar file. What is my problem? Am i just stupid or is there a bug? The main plugin is working fine.

**Comment by Dart2112** [comment]
You need to add the jar file from the releases page, you'll find the releases page on the right of the GitHub page for each plugin. then grab the latest version and download the .jar file and install that like you would any other plugin.

**Comment by baeumchen127** [comment]
oh ok, i am stupid :). I´ve never used github before. Thanks for your help.
