### ISSUE TITLE
Plugin lockup main thread while enabling

### ISSUE THREAD

**Issue by gilad8897** [LapisPlugins/AFKPlus#21]
Paperspigot 1.16.5
Many times when I start the server with the plugin - it says that in console and prevents the server from continuing loading other plugins which prevents the server from starting and allowing players to join.
Whenever the plugin is starting to load - the CPU usage drops to very little percentage, until I shut the server and remove the .jar of the plugin.
It is important to mention that it does not make the loading process stuck every single time, but when it does - it is the last plugin that seems to try to load in and whenever I remove it from the plugins folder - nothing is stuck.
https://gilad.is-inside.me/0IZXkmZd.png

**Comment by Dart2112** [comment]
I believe this was an issue with the auto-updater failing while on the main thread, resulting in a lockup. I've made the fix and will commit and update soon.
Sorry for the delays

**Comment by Dart2112** [comment]
Pushing out the update now
