### ISSUE TITLE
Suggestion: Make AFKPlusPrefix compatible with having other scoreboards.

### ISSUE THREAD

**Issue by sebastian-eb** [LapisPlugins/AFKPlus#22]
It seems to me that whenever **AFKPlusPrefix** is integrated into AFKPlus, it takes priority over any other previous existing scoreboards, hence rendering them no longer accessible or usable (Can't even set up new ones). You can't use this add-on along other popular datapacks such as Timber or MultiplayerSleep, as it blocks the /trigger function that they have.

**Comment by Dart2112** [comment]
I literally just told you about this on the correct issue, this issue is on the wrong GitHub page and is also redundant. closing
