### ISSUE TITLE
config reset to default settings on server restart

### ISSUE THREAD

**Issue by nimthepenguin** [LapisPlugins/AFKPlus#23]
players started noticing a significant drop in time to afk status being applied and then being kicked when settings hadnt been enabled originally. Upon inspection and multiple attempts to change the settings in config back to what the server members are used to noticed that while the changes are being applied immediately to the server they are being reverted back to the default each time the server restarts which happens automatically.

**Comment by Dart2112** [comment]
Make sure the config version is set to 7 if you are on the latest version. It's 3 am here so I'll sus it out when I wake up.

**Comment by nimthepenguin** [comment]
ok changed the config version to 7 and that fixed it thanks
