### ISSUE TITLE
1.16.5 Hex colors not working (afkplusprefix)

### ISSUE THREAD

**Issue by nikitushu2** [LapisPlugins/AFKPlus#25]
In afkplusprefix hex colors do not work. Same issue with the afkplus itself I guess.

None of these formats work:
- §x§f§e§4§a§4§9
- &x&f&e&4&a&4&9
- #fe4a49

**Comment by nikitushu2** [comment]
Also, afkplusprefix does not support even nonhex colors. The AFK prefix is always bold and red.

**Comment by Dart2112** [comment]
None of my plugins supports hex colours yet, that will be in the next major LapisCore update which will then roll out to the plugins.


> Also, afkplusprefix does not support even nonhex colors. The AFK prefix is always bold and red.

AFKPlusPrefix does support the old MC colour codes and it works fine on my test server as well as other peoples servers that I have seen. There must be another plugin messing with your prefixes for scoreboard teams

**Comment by nikitushu2** [comment]
In my case, old colors do not work in the tab itself (not scoreboard)

**Comment by Dart2112** [comment]
Cool, but tab prefix is actually scoreboard prefix with an option enabled to show it in the tab list. It's all the same string pulled from the config.

**Comment by nikitushu2** [comment]
Okay, thanks. Will be waiting for the hex update

**Comment by Dart2112** [comment]
Publishing updates now to address this
