### ISSUE TITLE
Perms and Config Issues

### ISSUE THREAD

**Issue by Notix7** [LapisPlugins/AFKPlus#26]
I have the config setup for it being the "admin" afk group disabling the kick action, yet players are still getting kicked, in luckperms I have certain players with the permission of afkplus.admin. Here is my config: https://pastebin.com/yZhhku15

**Comment by Dart2112** [comment]
Testing your config works fine for me, I get marked as AFK but not kicked. 
I can only suggest that you investigate if those players are being assigned permissions properly because it doesn't seem so

Also, CanUpdate should only be 0 or 1
