### ISSUE TITLE
AFK+ Mod-Relief suggestion

### ISSUE THREAD

**Issue by cytental** [LapisPlugins/AFKPlus#27]
im looking for a way to give my moderators and OP users a Break from constant questions and messages, would there be a way to add a FAKE AFK status that will stay toggled till you untoggle it. so my builders and mods can work in peace while everyone Thinks they are AFK? 

idea is from - https://www.spigotmc.org/resources/fakeafk.1655/ - but it doesnt have TITLEMANAGER support like AFK+ 
 Title Manager will not Show the AFK status with FAKEAFK Like AFK+ does, and Thats What i Need.

Please Let Mew Know if this is Possible.

**Comment by Dart2112** [comment]
It should be possible.

It might take me a little while to work out how I want to integrate it, but it should be doable.

**Comment by Dart2112** [comment]
I've added this just now.

It should work but I have done absolutely zero testing, you are welcome to compile and test it if you wish. I will test it later on before pushing out the update and you are also welcome to wait for that if you don't have the setup to compile and test it.

**Comment by cytental** [comment]
oh wow! amazing! how would i go about testing this function?

**Comment by Dart2112** [comment]
Add the FakeAFK permission to the rank of choice with a value of 1.
And then run "/afk -fake"
You can check the config on github to see how the permission is applied to the admin rank only by default.
Let me know if you have any issues or questions

**Comment by Dart2112** [comment]
rolled out to the public

**Comment by cytental** [comment]
@Dart2112 can you add instructions in the /afkplus help command menu?

also i updated the permissions but the command /afk -fake doesnt seem to be working, im not to sure what i could be doing wrong.

**Comment by Dart2112** [comment]
Can do

What is/isn't happening

**Comment by cytental** [comment]
> 
> 
> Can do
> 
> What is/isn't happening

https://pastebin.com/iuGjKY8H here is my config

**Comment by Dart2112** [comment]
Fake afk need to be 1. It's a true or false value so it'll be either one or zero.

**Comment by cytental** [comment]
> 
> 
> FakeAFK permission needs to be 1. It's a true or false value so it'll be either one or zero.

so i changed to 1 and when i type "/afk -fake" it says "player not found"

**Comment by Dart2112** [comment]
can you verify that you are on the latest spigot version. it should give you a different error if you are on the latest

**Comment by Dart2112** [comment]
confirmed working for me on the spigot version

`[12:13:26 INFO]: dart2112[/127.0.0.1:33106] logged in with entity id 320 at ([world]-186.65469991496855, 79.0, 73.72059909853809)`

`[12:13:51 INFO]: dart2112 issued server command: /afk -fake`

`[12:13:51 INFO]: [AFK+] dart2112 is now AFK`

**Comment by cytental** [comment]
i guess its using essentialsx somehow for afk. im trying to disable it.

**Comment by cytental** [comment]
![Uploading C6D5AFB1-1FFF-42F6-B66E-8E513542677D.jpeg…]()

**Comment by Dart2112** [comment]
can you try just the /afk and verify that AFKPlus is the one that responds
also, what is it showing to the player?

**Comment by cytental** [comment]
hey totally my fault on my end dont mind me, i had 3.3.0 not 3.3.2 installed by accident, i fixed it and it works, though i did notice that if you have essentials if you move it will still put you as back from afk so i just had to tweak the essentials config to make movement and such not a trigger, everything works absolutely perfect now, you are a Saint!

**Comment by Dart2112** [comment]
Glad to hear it, no worries
