### ISSUE TITLE
Not detecting Vanish from CMI

### ISSUE THREAD

**Issue by KingDingers** [LapisPlugins/AFKPlus#29]
Seems like Vanish from CMI is not being detected as actually being vanished. Broadcast while Vanished is false in the config. Not sure if this would be a bug or a request to add support for CMI Vanish. Thanks for any assistance!
Using PurPur 1.16.5

**Comment by Dart2112** [comment]
https://github.com/Zrips/CMI/issues/5131
it seems that this is a known issue. Since CMI isn't open source I can't see how they handle vanish. Both essentials and VanishNoPacket set a variable on the player that AFKPlus can see, this is how I detect vanish. It seems that CMI isn't doing that.

**Comment by KingDingers** [comment]
Oh gotcha, I will give VanishNoPacket a shot then. Appreciate the explanation and quick response!
