### ISSUE TITLE
Add option to disable broadcasts

### ISSUE THREAD

**Issue by Dart2112** [LapisPlugins/AFKPlus#3]
It has come to my attention that @Apecengo has forked AFK Plus to implement this feature, it shouldn't be necessary for someone to maintain their own fork to have an option that is this simple

Should be as simple as a config option for broadcasting to all players, just the player that has had a state change, or none of the above.

**Comment by Apecengo** [comment]
Thanks!

**Comment by Dart2112** [comment]
Fixed in commit 9ed5fd7aa07636bcedbd3ebba72a08e14d3c09bf
