### ISSUE TITLE
Auto reconnect detection and mitigation

### ISSUE THREAD

**Issue by Uboaaaaa** [LapisPlugins/AFKPlus#30]
There's been a popular client-side mod named [Autoreconnect](https://www.curseforge.com/minecraft/mc-mods/autoreconnect), which would reconnect the player to the server whenever they've been kicked due to afk. As players' afk timer resets after they log back, it kinda renders the effort of the plugin pointless.

Suggested solution: If the player connects within a short timeframe after the action is performed, keep their afk state and the timer accumulating. Then there can be another sets of action to execute after it hits higher values. 

Which means players get a time frame to ''prove'' that they are actually in front of their screen after they relogged (by looking around etc). If they failed to be unmarked as afk (for multiple sessions) the server can, for example, prevent them from connecting for a period.

**Comment by Dart2112** [comment]
What I Might do is implement this as an additional plugin so that I can go all out with it and offer a whole ton of settings to customize it without flooding the main plugin with config options. When I push the addon to GitHub I'll transfer this issue to it

**Comment by srnyx** [comment]
> What I Might do is implement this as an additional plugin so that I can go all out with it and offer a whole ton of settings to customize it without flooding the main plugin with config options. When I push the addon to GitHub I'll transfer this issue to it

Could you possibly make it an addon to AFKPlus? Where if installed it will add either a file or folder to `plugins/AFKPlus` where all of its settings will be.

**Comment by Dart2112** [comment]
> > What I Might do is implement this as an additional plugin so that I can go all out with it and offer a whole ton of settings to customize it without flooding the main plugin with config options. When I push the addon to GitHub I'll transfer this issue to it
> 
> Could you possibly make it an addon to AFKPlus (maybe even installable via a `addons` folder in `plugins/AFKPlus` [`plugins/AFKPlus/addons`], which could also open the path for user-made add-ons)? Where if installed it will add either a file or folder to `plugins/AFKPlus` where all of its settings will be.

This is already the case. The AFKPlus API is publically accessible to other plugins and my other addons are installed as their own plugins that hook into the API. Users are welcome to make their own addons, and I can even add them to the plugin page on spigot if its something others might ger use out of

**Comment by srnyx** [comment]
> This is already the case. The AFKPlus API is publically accessible to other plugins and my other addons are installed as their own plugins that hook into the API. Users are welcome to make their own addons, and I can even add them to the plugin page on spigot if its something others might ger use out of

Ah, right. Well, the issue with that is having 5 different plugin folders for 1 "actual" plugin.

**Comment by Dart2112** [comment]
AFKPlusReconnect now exists. It will be published shortly in the releases tab on this GitHub page
https://github.com/Dart2112/AFKPlusReconnect

**Comment by Dart2112** [comment]
If you have any issues or requests on how to improve that add on please make an issue on its GitHub page and not here
