### ISSUE TITLE
Idle detector

### ISSUE THREAD

**Issue by DarkCynicism** [LapisPlugins/AFKPlus#32]
Suggestion: Perhaps some additional code to detect whether pitch/ yaw has changed, in order to prevent 'AFK Pools' i.e players using boats/ water to keep moving while not actively being at their keyboard

**Comment by Dart2112** [comment]
https://github.com/LapisPlugins/AFKPlus/blob/master/src/main/resources/config.yml#L77

`#Enabling aggressive AFK detection will tighten tolerances on AFK machines but may slow down the reaction time of
#removing players from AFK and may also mark players as AFK when they are simply not moving much, this should only
#be enabled if you are having trouble with players using machines like AFK fishing farms
AggressiveAFKDetection: false`

It does already exist
