### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by TheOneEx** [LapisPlugins/AFKPlus#36]
[14:01:55 ERROR]: Could not load 'plugins/AFKPlus.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/lapismc/afkplus/AFKPlus has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by Dart2112** [comment]
https://www.spigotmc.org/threads/afk.210665/page-15#post-4161776

You need to update your java version
