### ISSUE TITLE
Configurable sensitivity/threshold for detections

### ISSUE THREAD

**Issue by srnyx** [LapisPlugins/AFKPlus#38]
If the player moves their camera even the tiniest bit (0.1), it unAFKs them. Same with player movement.
I suggest a threshold for unAFKing the player.

Example 1: If the camera movement threshold is set to 5, the player would have to move their camera 5 degrees (instead of 0.1) for it to unAFK them
Example 2: If the player movement threshold is set to 3, the player would have to move their player 3 blocks (instead of 0.001 [I think it's this, I don't use player movement detection]) to unAFK them.

It doesn't have to be limited to only player/camera movement though. You could add a config option for each type of detection.

**Comment by Dart2112** [comment]
I'll have a look at this. Unfortunately I use player move events which fire very rapidly meaning its hard to tell how far the player is moving

**Comment by Dart2112** [comment]
I'm gonna play around with a running tally kinda system. Not sure how well it will work but I will give it a shot

**Comment by Dart2112** [comment]
In latest update that is pushing out now

**Comment by srnyx** [comment]
> In latest update that is pushing out now

Thank you!! This makes the plugin a ton better!!!
