### ISSUE TITLE
Double messages sent when doing /eafk

### ISSUE THREAD

**Issue by srnyx** [LapisPlugins/AFKPlus#39]
Each red box indicates a time I did `/eafk`
*I have `/afk` disabled in EssentialsX (`disabled-commands`)*
![image](https://user-images.githubusercontent.com/25808801/141664345-529b47fb-77a8-43f4-9e2b-ea78cfa18f31.png)

**Comment by Dart2112** [comment]
Fixed in update being pushed out now
