### ISSUE TITLE
Add placeholder variables for PAPI

### ISSUE THREAD

**Issue by Jadiction** [LapisPlugins/AFKPlus#4]
Customizable variables for when AFK is true or false. This would be nice to add to plugins that change the tab name, abovehead name, chat name, etc. 

For example- 

  The placeholder: 

    %afkplus_status%

  Config setting:

    status:

      true: "&c(AFK)&r"

      false: ""

**Comment by Dart2112** [comment]
I've just whipped up an addon that should do this

https://github.com/Dart2112/AFKPlusPAPI

You're welcome to contribute/fork but it should do what you have asked with the placeholders AFKPlus_Status and AFKPlus_AFKTime

**Comment by Jadiction** [comment]
Thanks! Can you add the compiled version in https://github.com/Dart2112/AFKPlusPAPI/releases ? That way it's easier.

**Comment by Dart2112** [comment]
Done

**Comment by Jadiction** [comment]
Thanks again!
