### ISSUE TITLE
Cannot invoke "org.bukkit.OfflinePlayer.getUniqueId()" because "op" is null

### ISSUE THREAD

**Issue by srnyx** [LapisPlugins/AFKPlus#40]
Purpur 1.17.1
AFKPlus v3.3.8
https://paste.srnyx.xyz/ohicecefag.md

**Comment by Dart2112** [comment]
Very interesting, not an error I would expect was possible. I'll do some digging

**Comment by Dart2112** [comment]
This was an issue with LapisCore's PAPI hook not being updated to a newer version. It should be fixed with the newest AFKPlusPapi update. Make sure to install the AFKPlus update as well, it will be out soon and they both need each other
