### ISSUE TITLE
AFK status doesn't automatically unset after using /afk command

### ISSUE THREAD

**Issue by raffel080108** [LapisPlugins/AFKPlus#41]
When a player uses /afk command they will not be automatically kicked out of this state (unless you rejoin). You can run around, attack things, place and break things, heck you can even die and it won't toggle your AFK-state back. I took any exta permissions from me aswell as OP, so that had nothing to do with it
It's not a huge issue, but should still be fixed in my opinion. The thing I did for now is simply revoke the permission to manually toggle /afk

_config.yml (when testing the issue):_
```
ConfigVersion: 10

[...]

#A player will be set as AFK if they don't interact with the world
#What should be counted as an interaction?
#Set too false to ignore
EnabledDetections:
  #Sending chat messages
  Chat: true
  #The players head/body rotating in place
  Look: true
  #Moving in the x,y,z directions
  Move: true
  #Attacking entities
  Attack: false
  #Running commands
  Command: true
  #Right-clicking blocks
  Interact: true
  #Placing blocks
  BlockPlace: true
  #Breaking blocks
  BlockBreak: true

#Movement magnitude means that players need to move or look a certain distance before they will be marked as not AFK
MovementMagnitude:
  #Should the movement magnitude system be enabled
  Enabled: true
  #How far does the player need to move every second to be counted as moving
  PositionTrigger: 1.0
  #What angle does the player need to look every second to be counted as looking
  LookTrigger: 5.0
  
  [...]
  
#You no longer need to list values that differ from the default values below
# Default=0, Priority=0, AFKSelf=1, AFKOthers=0, FakeAFK=0, TimeToAFK=30, TimeToWarning=90, TimeToAction=120 and CanUpdate=0
Permissions:
  afkplus,player:
    #Who should get this permission without it being given, 0 = no one, 1 = everyone, 2 = Ops
    Default: 1
    #If a player has more than 1 permission they will be given the one with the highest priority
    Priority: 1
    #Can the player set themselves as AFK with the /afk command
    AFKSelf: 1
    #Can the player set others as AFK with the /afk command
    AFKOthers: 0
    #How many seconds of inactivity are required before they will automatically be set as AFK
    #Set to -1 if the player shouldn't be automatically placed in AFK
    TimeToAFK: 90
    #How many seconds of AFK are required before the player is warned about action being taken
    #Set to -1 to disable warnings for this permission
    TimeToWarning: -1
    #How many seconds of AFK are required before the player is acted upon
    #Set to -1 to disable actions for this permission
    TimeToAction: -1
    #Can this player use the update command to install new versions
    CanUpdate: 0
[...]

**Comment by raffel080108** [comment]
Update: I tested around a bit more and it seems there are 2 types of an AFK-State. One is the automatically caused one and the second one the manually caused one (by using /afk). Both display the same messages but do not work together with each other. Also only the manual state causes the %AFKplus_status% placeholder (from AFKPlusPapi) to update
It would be nice for both states to work as one and that one state also updating the placeholder

**Comment by Dart2112** [comment]
I'm actually going to reopen this because I think I know what caused it and it is something that should work

Note to self, check if online players are generated in on enable after being closed out in on disable

**Comment by raffel080108** [comment]
I didn't understand that.. But alright, I guess

**Comment by Dart2112** [comment]
Made a change that should have fixed this

> I'm actually going to reopen this because I think I know what caused it and it is something that should work
> 
> Note to self, check if online players are generated in on enable after being closed out in on disable
