### ISSUE TITLE
Add a /reload command

### ISSUE THREAD

**Issue by raffel080108** [LapisPlugins/AFKPlus#42]
If possible, please add a /reload command, that updates the config while the plugin is running

**Comment by Dart2112** [comment]
it should automaticlly reload them when you edit the file. do you see anything in console when you edit configs?

**Comment by raffel080108** [comment]
I don't know, I didn't test that. But the changes didn't apply, at least not changes to messages.yml. And when I reload the plugin using another plugin (called Plugman) things mess up until I restart the server

**Comment by raffel080108** [comment]
I can test a little bit later, I currently am having other issues (related to my host) with my server, that I'm working on. So I'll do it once I'm over with that
