### ISSUE TITLE
announces vanish players

### ISSUE THREAD

**Issue by KonstaVilkman** [LapisPlugins/AFKPlus#48]
Players who are in vanish are still able to get announcements making it really clear that you are still on the server

**Comment by Dart2112** [comment]
This is accounted for with the Broadcast.Vanish setting

When set to false, players will not see the start and stop messages for vanished players. The vanished player and the console will still see the messages though

The plugin checks for vanish using the code snippet below, the issue may be the plugin you are using for vanish doesn't update this value

`
Player.getMetadata("vanished")
`

**Comment by Dart2112** [comment]
Lack of response from Issue opener, closing. Reopen if you are still having the issue and can provide more info
