### ISSUE TITLE
Allow teleportation while AFK

### ISSUE THREAD

**Issue by WarnDa** [LapisPlugins/AFKPlus#49]
Hello,

I just switched from UltraAFK to AFK+ again (I was using afk+ in 2018 lol, long time ago !!)

And the thing I was used in ultraafk was to teleport the player to the afkzone after 10mn of afk (and this time depend on player rank, vip are teleported after 10mn, vip+ after 20mn)
And when they were back, they moved and it teleported them again on the last point before they afk.

So like hypixel system :)

Do you think it would be possible to add that ? :)
If needed I can do a small tips for this

**Comment by Dart2112** [comment]
https://github.com/Dart2112/AFKPlusEventCommands

You might be able to put teleport commands into this add-on
I'm not sure if the player "moving" when they get teleported would be an issue. But if it is then I can update to add-on to fix it

**Comment by WarnDa** [comment]
I don't understand why I need to use AFKPlusEventCommands, I used default config of AFKPlus and it does the same things
> Commands:
  Action: "essentials:warp invest [PLAYER]"
  AFKStart: ""
  AFKStop: "sudo [PLAYER] back"
  Warn: ""

I set this, but I got an issue : 
- When you are teleported, you are set unafk BUT it doesn't tell you "you are not afk, welcome back"
instead, it will set your afk timer back to 0, so after X seconds you are considered afk again, and after XX seconds you are teleported again.

So, it doesn't trigger the "AFKStop" command, but it doesn't consider me still afk (idk if you understood, but if possible you should try yourself)

**Comment by WarnDa** [comment]
![image](https://user-images.githubusercontent.com/31826333/187259862-e27c1452-7dd8-4247-b672-293788d528cf.png)
Example (it's french)
- "tu es désormais considéré absent" means 'you are now afk', so the message that is send by the plugin when player goes afk)
- "téléportation vers investissement" is the "Action: "essentials:warp invest [PLAYER]"

**Comment by Dart2112** [comment]
I believe I found the issue with how the command is executed. here is a beta version to test with. It should run the command to teleport without any issues to do with afk state
[AFKPlus.zip](https://github.com/LapisPlugins/AFKPlus/files/9450010/AFKPlus.zip)

**Comment by WarnDa** [comment]
Hello,
thanks for this !

There is still the same issue as before, when I got teleported, it will still set him afk again and again

**Comment by WarnDa** [comment]
Hope you are doing well, any news ? :)

**Comment by WarnDa** [comment]
Hello,
I'm just waiting for this fix to use the plugin, hope you'll keep me informed ! 👍

**Comment by Dart2112** [comment]
Sorry, I have been sick for the last couple of weeks plus uni. I am still working on getting this done but life gets in the way

**Comment by WarnDa** [comment]
> Sorry, I have been sick for the last couple of weeks plus uni. I am still working on getting this done but life gets in the way

Good luck for school :)
Anything I can help you with ? I'm really waiting for this fix to use this plugin, I don't get afk plugin currently :(

**Comment by WarnDa** [comment]
Hello,
I'm really need the plugin but I can't help you, so I don't know what to do, it's been two months :/

**Comment by Dart2112** [comment]
> 

I found the issue, you are teleporting as the Action. The action must either remove the player from the server or make them not AFK (as is explained in the comment above the commands section). If you just want AFK players to be in a special spot then you have to use AFK start or maybe AFK warn.

**Comment by Dart2112** [comment]
I wouldn't recommend using warn as not all players will reach the warning but they will all run the back command when they exit AFK causing erroneous teleports. Using the following config (taken from your own comment) has been tested and is working

Commands:
  Action: "essentials:warp invest [PLAYER]"
  AFKStart: "essentials:warp afk [PLAYER]"
  AFKStop: "sudo [PLAYER] back"
  Warn: ""

**Comment by WarnDa** [comment]
I just tried it, and it doesn't work, as command are executed AFTER player being afk, it teleports him, and make him unafk, so like before, he get teleported indefinitely

**Comment by WarnDa** [comment]
If I pay you to make the system I wanted, would you accept ?
(all players are afk after 5mn of inactivity, and they will be teleported to afk zone after X minute depending on their rank)

**Comment by Dart2112** [comment]
> If I pay you to make the system I wanted, would you accept ? (all players are afk after 5mn of inactivity, and they will be teleported to afk zone after X minute depending on their rank)

If you fork AFKPlus and add me as a contributor to the fork I can just make the required changes in your forked version. It's not too difficult, it's just hard to do without screwing over the main version.

**Comment by WarnDa** [comment]
> > If I pay you to make the system I wanted, would you accept ? (all players are afk after 5mn of inactivity, and they will be teleported to afk zone after X minute depending on their rank)
> 
> If you fork AFKPlus and add me as a contributor to the fork I can just make the required changes in your forked version. It's not too difficult, it's just hard to do without screwing over the main version.

https://github.com/SmeltBlock/AFKPlus

**Comment by Dart2112** [comment]
Pushing the changes now. I quickly tested it and I got teleported to the afk warp when I would normally be kicked. and I stayed AFK. Then when I moved I was teleported back to where I was before I went AFK. Let me know if it has any issues.

**Comment by WarnDa** [comment]
Possible to compile it please so I can test, I didn't setup anything to compile

**Comment by WarnDa** [comment]
> Pushing the changes now. I quickly tested it and I got teleported to the afk warp when I would normally be kicked. and I stayed AFK. Then when I moved I was teleported back to where I was before I went AFK. Let me know if it has any issues.

can't compile due to https://pastebin.com/htjqr0Lh

**Comment by Dart2112** [comment]
[AFKPlus.zip](https://github.com/LapisPlugins/AFKPlus/files/9911602/AFKPlus.zip)
That zip has the compiled jar inside plus the cloned repo after the build command was run
