### ISSUE TITLE
Plugin does not shut down async tasks properly

### ISSUE THREAD

**Issue by metzg** [LapisPlugins/AFKPlus#5]
Seeing this message when shutting down the server (Paper 1.16 build 25):

```[19:14:06] [Server thread/ERROR]: Nag author: 'Dart2112' of 'AFKPlus' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.```

**Comment by Dart2112** [comment]
Fixed in 3.1.8
It was the AFK Machine Detection thread that wasn't being shut down, this has been fixed
