### ISSUE TITLE
AFK lingers when game ends

### ISSUE THREAD

**Issue by AlphaBeta906** [LapisPlugins/AFKPlus#50]
The AFK role lingers when game ends from AFKPlusPrefix. I think it means that AFK also lingers. Can you make it that it resets when game ends?

**Comment by Dart2112** [comment]
What do you mean by "game ends"?

**Comment by AlphaBeta906** [comment]
like when you shutdown the server

**Comment by Dart2112** [comment]
Fixed in latest release

**Comment by AlphaBeta906** [comment]
Follow up question, is the release already made or just made?

**Comment by Dart2112** [comment]
> Author

https://github.com/Dart2112/AFKPlusPrefix/releases/tag/1.3.4

**Comment by AlphaBeta906** [comment]
Oh. Thank you!
