### ISSUE TITLE
How to use the afkplus prefix

### ISSUE THREAD

**Issue by KukulDev** [LapisPlugins/AFKPlus#55]
Hi, i downloaded AFKPlus and AFKPlusPrefix and i also have TAB plugin and when player is afk it wont display in tab, any fixes?

**Comment by Dart2112** [comment]
Unfortunately, AFKPlusPrefix doesn't play nice with other plugins that use scoreboards. You can try enabling the compatibility mode but I can't guarantee it will help. This incompatibility is why AFKPlusPrefix is an add-on.
