### ISSUE TITLE
How to disable kicking from the server for AFK for players? 

### ISSUE THREAD

**Issue by Savranchuk** [LapisPlugins/AFKPlus#61]
Tell me please. How to disable kicking from the server for AFK for players? Which point is responsible for this? Can not understand..

**Comment by Dart2112** [comment]
If you want everything else to work, have players stay AFK until they return, you need to disable the TimeToWarning and TimeToAction settings in the permissions section of the config.yml.

As the comments in the config.yml say "Set to -1 to disable actions for this permission"
