### ISSUE TITLE
If player have a collision with another or entity > the player quit AFK

### ISSUE THREAD

**Issue by PatalkokGIT** [LapisPlugins/AFKPlus#63]
If player have a collision with another or entity > the player quit AFK

**Comment by Dart2112** [comment]
This is a known issue and there are a few options to try and fix it. But none of them are perfect.

The easy but much less perfect option:
enable bump protection in the config. Under Protections, the first option is bump. Enabling this will fix the issue but it also has its downsides, mainly that players won't be able to walk while AFK and will need to jump or interact with the world in some other way to be able to leave AFK.

The less compatible but much better option:
you can install AFKPlusPrefix and leave ShouldCollide set to false. This will stop AFK players from being bumped by non-AFK players.

For mobs there is one simple fix, there is a protection called MobTargeting. Enable this and hostile mobs won't target AFK players and therefore won't bump them out of AFK.

**Comment by PaBox** [comment]
Hi, we are having trouble getting this to work on our bungeecord-/paper-server network, players can push others out of afk even though we do have set `Bump: true` and the comment tells this:
```yaml
  # When enabled AFK players will not be able to move in the x and z directions while AFK.
  # This stops them being pushed out of AFK by players bumping into them
  # This is implemented better in AFKPlusPrefix, but that addon is not compatible with all servers
  # so this is a different implementation of the fix
```

Players can move in the x and z direction whilst afk against advertised and are not held on the spot. What should this option specifically do?

Thanks for all the works, greetings!

**Comment by Dart2112** [comment]
It seems that the comment is out of date. The current method is checking if a player or monster is within half a block of the player when they move and cancelling the move event if that is true. I'll do some testing with your config and see if I can reproduce the issue.
