### ISSUE TITLE
AFKPlusPapi Placeholder

### ISSUE THREAD

**Issue by BlueTheSlue** [LapisPlugins/AFKPlus#68]
Is there anyway to have the %AFKPlus_AFKTime% placeholder, show the time format just like %TotalTimeAFK%. Cause its quite confusing right now, and it seems like the time is off with that placeholder too.

**Comment by Dart2112** [comment]
[AFKPlusPAPI.zip](https://github.com/user-attachments/files/16828954/AFKPlusPAPI.zip)
Here is an updated PAPI jar that should use PrettyTime for both time-based placeholders. Give it a shot and let me know if there are any issues

**Comment by BlueTheSlue** [comment]
Thanks it works now

**Comment by Dart2112** [comment]
Awesome, I'll post a new update in https://github.com/Dart2112/AFKPlusPAPI
